### PR TITLE
ImGui widgets record their dimensions, invalidate lower uis

### PR DESCRIPTION
**Pull request by db48x**
The invalidation logic is already there, we just have to set the `dimensions` so that it knows what we drew over.

### CODE REVIEW

**Comment by katemonster33** [comment]
@db48x hey, I don't know if you intended this, but imconfig.h is an ImGui header, and you're including CDDA headers into it. I can't accept this, convert the ImVec2 to a point manually in your redraw function

**Comment by db48x** [comment]
Yea, that’s how it’s supposed to work. imconfig.h won’t change in future releases of ImGui. It exists so that we have a convenient place to put these types of conversions and other configuration choices that won’t cause merge conflicts when we upgrade to a new ImGui release in the future.

**Comment by katemonster33** [comment]
The file does change, but it's more the principle that you're having a third party library link back into CDDA. its just not a good idea to write things this way. If point.h was an STL file i wouldn't care

**Comment by db48x** [comment]
I guess the ImGui folks have different principles, because this is definitely how they intend ImGui to be customized.

I suppose I could move the definition of `IM_VEC2_CLASS_EXTRA` in to point.h, just ahead of where it will include imgui.h. However, that will cause a potential foot–gun down the road: any file that includes imgui.h instead of point.h will get a different definition of the `ImVec2` class. Do you really want that?

**Comment by katemonster33** [comment]
> I guess the ImGui folks have different principles, because this is definitely how they intend ImGui to be customized.
> 
> I suppose I could move the definition of `IM_VEC2_CLASS_EXTRA` in to point.h, just ahead of where it will include imgui.h. However, that will cause a potential foot–gun down the road: any file that includes imgui.h instead of point.h will get a different definition of the `ImVec2` class. Do you really want that?

I was just thinking we could get by without any copy constructor, but I suppose I see what you're saying. I guess do it whatever way you want and I'll merge it when it's ready.

**Comment by katemonster33** [comment]
@db48x looking to rebase my branch against master soon, think you'll have time to get to this over the weekend?

**Comment by db48x** [comment]
I already did; see 45b6a22 above.

**Pull request merged**
