### PR TITLE
rewrite some uses of the uilist callback refresh method

### PR DESCRIPTION
**Pull request by db48x**
1 down, 11 to go.

### CODE REVIEW

**Comment by db48x** [comment]
Screenshot from 2024-04-23 16-53-56

I don’t quite know what is going wrong here. The text I am passing to `draw_colored_text` looks right to me:

    (gdb) p text
    $1 = "Pocket 3:\nVolume: <color_c_yellow>1.08</color> L  Weight: <color_c_yellow>8.82</color> lbs\nItem length: <color_c_yellow>0</color> in. to <color_c_yellow>6</color> in.\nBase moves to remove item: <color"...

**Comment by db48x** [comment]
Turns out the problem was that the “lines” we were printing contained newline characters. ImGui doesn't take them into account when it moves its own cursor, so the next thing we printed would end up in the wrong place.

**Comment by db48x** [comment]
That kinda worked:

Screenshot from 2024-04-25 10-35-11

**Comment by db48x** [comment]
That didn’t:

Screenshot from 2024-04-25 18-42-30

**Comment by db48x** [comment]
Now that’s more like it:

Screenshot from 2024-04-25 19-46-26

**Comment by db48x** [comment]
looking pretty good:

Screenshot from 2024-04-25 19-50-09

Though of course I really ought to render it using the real map view tiles. It probably wouldn’t be all that hard… but I think that I am too tired to mess with it more tonight.

**Comment by db48x** [comment]
ld: obj/tiles/wish.o: in function `string_id<mutation_category_trait>::operator->() const':
    /home/db48x/src/cataclysm/uilist/src/string_id.h:291: undefined reference to `string_id<mutation_category_trait>::obj() const'

Yay.

**Comment by db48x** [comment]
I think there’s only this one thing left to implement, before the catacurses::window can be deleted:

Screenshot from 2024-04-27 19-37-50

Unfortunately the code is annoying (not designed well) and there are a lot of little bugs and I am too tired.

**Comment by db48x** [comment]
This is pretty complete, aside from a few bugs and possibly a few left over member variables that could be deleted. A review might be useful. And while  I would like to circle back around and see if I can get the teleporter menu to draw the overmap using overmap sprites instead of text, it’s more of a stretch goal than anything else.

**Comment by katemonster33** [comment]
sorry, i forget that GH doesnt ever show me PR's against my branch, i can look at this tomorrow

**Comment by katemonster33** [comment]
I'll just merge this and we can move discussion into the main pr

**Pull request merged**
